### ISSUE TITLE
Error running this script

### ISSUE THREAD

**Issue by gunnicus** [awslabs/sbs-iot-data-generator#2]
PS C:\Users\water> cd 'd:\AWS'; ${env:PYTHONIOENCODING}='UTF-8'; ${env:PYTHONUNBUFFERED}='1'; & 'python' 'c:\Users\water\.vscode\exERED}='1'; & 'python' 'c:\Users\water\.vscode\extensions\ms-python.python-2018.9.0\42' 'd:\AWS\sbs.py'pythonFiles\experimental\ptvsd_launcher.py' '53342' 'd:\AWS\sbs.py'
Traceback (most recent call last):
  File "c:\Users\water\.vscode\extensions\ms-python.python-2018.9.0\pythonFiles\experimental\ptvsd_launcher.py", line 118, in <module>
    vspd.debug(filename, port_num, '', '', run_as)
  File "c:\Users\water\.vscode\extensions\ms-python.python-2018.9.0\pythonFiles\experimental\ptvsd\ptvsd\debugger.py", line 37, in debug
    run(address, filename, *args, **kwargs)
  File "c:\Users\water\.vscode\extensions\ms-python.python-2018.9.0\pythonFiles\experimental\ptvsd\ptvsd\_local.py", line 79, in run_file
    run(argv, addr, **kwargs)
  File "c:\Users\water\.vscode\extensions\ms-python.python-2018.9.0\pythonFiles\experimental\ptvsd\ptvsd\_local.py", line 140, in _run
    _pydevd.main()
  File "c:\Users\water\.vscode\extensions\ms-python.python-2018.9.0\pythonFiles\experimental\ptvsd\ptvsd\_vendored\pydevd\pydevd.py", line 1751, in main
    debugger.connect(host, port)
  File "c:\Users\water\.vscode\extensions\ms-python.python-2018.9.0\pythonFiles\experimental\ptvsd\ptvsd\_vendored\pydevd\pydevd.py", line 1107, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "c:\Users\water\.vscode\extensions\ms-python.python-2018.9.0\pythonFiles\experimental\ptvsd\ptvsd\_vendored\pydevd\pydevd.py", line 1114, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "c:\Users\water\.vscode\extensions\ms-python.python-2018.9.0\pythonFiles\experimental\ptvsd\ptvsd\_vendored\pydevd\_pydev_imps\_pydev_execfile.py", line 25, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "d:\AWS\sbs.py", line 60
    print data
             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(data)?

**Comment by kanumuru** [comment]
The code you have downloaded is in python version2 
but you are running the script using python version 3.\
Now migrate your code to python3 or else install python version 2 and run again
Hope it will help you.

**Comment by anhdungadg** [comment]
> Now migrate your code to python3 or else install python version 2 and run again

Thanks you so much.

**Comment by pabloariasmora** [comment]
Hi @gunnicus 

I've submitted PR #4  that addresses this issue by modernizing the codebase to Python 3.

The PR is currently waiting for review and merge. Once merged, this will resolve the syntax errors you encountered and provide additional functionality to make the tool more reliable.

You can find the full details of the changes in PR #4 . Please feel free to review and provide any feedback.
